"""Assignment 1 - Grocery Store Events (Task 2)

CSC148 Winter 2024
Department of Computer Science,
University of Toronto

This code is provided solely for the personal and private use of
students taking the CSC148 course at the University of Toronto.
Copying for purposes other than this use is expressly prohibited.
All forms of distribution of this code, whether as given or with
any changes, are expressly prohibited.

All of the files in this directory are
Copyright (c) Jonathan Calver, Diane Horton, Sophia Huynh, Joonho Kim and
Jacqueline Smith.

Module Description:

When you are done Task 2, this file should contain all the classes
necessary to model the different kinds of events in the simulation.
"""
from __future__ import annotations

from io import StringIO
from typing import TextIO
from store import GroceryStore, Customer, Item, NoAvailableLineError


class Event:
    """An event in our grocery store simulation.

    Events have an ordering based on the event timestamp. For any two events
    e1 and e2, e1 < e2 iff event e1 has a timestamp that is less than event e2.
    This signifies that e1 happens before e2.

    This is an abstract class and should not be instantiated.

    Attributes:
    - timestamp: The time when this event occurs.

    Representation Invariants:
    - timestamp >= 0
    """
    timestamp: int

    def __init__(self, timestamp: int) -> None:
        """Initialize an Event with a given timestamp.

        Preconditions:
            - timestamp >= 0

        >>> Event(7).timestamp
        7
        """
        self.timestamp = timestamp

    # The following three methods allow for comparison of Event instances
    # using the standard comparison operators, such as ==, <, and <=.
    # All methods simply perform the desired comparison on the 'timestamp'
    # attribute of the two events.
    # def __str__(self) -> None:
    #     """
    #     Print the event
    #     """
    #     return "Event ts is : " + str(self.timestamp)

    def __eq__(self, other: Event) -> bool:
        """Return whether this Event is equal to <other>.

        Two events are equal iff they have the same timestamp.

        >>> first = Event(1)
        >>> second = Event(2)
        >>> first == second
        False
        >>> second.timestamp = first.timestamp
        >>> first == second
        True
        """
        return self.timestamp == other.timestamp

    def __lt__(self, other: Event) -> bool:
        """Return True iff this Event is less than <other>.

        >>> first = Event(1)
        >>> second = Event(2)
        >>> first < second
        True
        >>> second < first
        False
        """
        return self.timestamp < other.timestamp

    def __le__(self, other: Event) -> bool:
        """Return True iff this Event is less than or equal to <other>.

        >>> first = Event(1)
        >>> second = Event(2)
        >>> first <= first
        True
        >>> first <= second
        True
        >>> second <= first
        False
        """
        return self.timestamp <= other.timestamp

    def do(self, store: GroceryStore) -> list[Event]:
        """Perform this event as specified in the A1 handout, and return any
        events generated by doing so.
        """
        raise NotImplementedError


# TODO: create subclasses for the different types of events below.
class CustomerArrival(Event):
    """A customer arrives at the checkout area ready to join a line and
    check out.

    Attributes:
    - customer: The arriving customer
    """
    timestamp: int
    customer: Customer

    def __init__(self, timestamp: int, c: Customer) -> None:
        """Initialize a CustomerArrival event with the given <timestamp>
        and customer <c>.

        If the customer's arrival time is None, set it now to record
        the fact that this is the time when they first arrived at the
        checkout area. (This is the start of their waiting time.)

        Preconditions:
        - timestamp >= 0
        """
        # TODO: Implement this method
        super().__init__(timestamp)
        if c.arrival_time is None:
            c.arrival_time = timestamp
        self.customer = c

    def do(self, store: GroceryStore) -> list[Event]:
        """
        If a customer joins an empty checkout line, a new checkout Started
        event is added with the same timestamp as the Customer Arrival event.
        If there is no line for the customer to join, a new Customer Arrival
        event is generated for them, with a timestamp that is one step
        in the future.
        """
        try:
            line_number = store.enter_line(self.customer)
            # If the line is empty(First in line is the cx)
            if (store.first_in_line(line_number) and
                (store.first_in_line(line_number).name == self.customer.name)):
                checkout_event = CheckoutStarted(self.timestamp, line_number)
                return [checkout_event]
            else:
                return None
        except NoAvailableLineError:
            arrival_event = CustomerArrival(self.timestamp + 1, self.customer)
            return [arrival_event]

class CheckoutStarted(Event):
    """A customer starts the checkout process in a particular checkout line.

    Attributes:
    - line_number: The number of the checkout line.
    """
    timestamp: int
    line_number: int

    def __init__(self, timestamp: int, line_number: int) -> None:
        """Initialize a CheckoutStarted event with the given <timestamp>
        and <line_number>.

        Preconditions:
        - timestamp >= 0
        - line_number >= 0
        """
        # TODO: Implement this method
        super().__init__(timestamp)
        self.line_number = line_number

    def do(self, store: GroceryStore) -> list[Event]:
        """
        If a customer begins checking out, a new Checkout Completed event is
        added with the same timestamp as the Checkout Started timestamp, plus
        the appropriate amount of time based on the type of checkout line and
        the time required for the customer’s items.
        """
        checkout_time = store.next_checkout_time(line_number=self.line_number)
        cx = store.first_in_line(self.line_number)
        checkout_complete_event = CheckoutCompleted(self.timestamp + checkout_time, self.line_number, cx)
        return [checkout_complete_event]

class CheckoutCompleted(Event):
    """A customer finishes the checkout process.

    Attributes:
    - line_number: The number of the checkout line where a customer
      is finishing.
    - customer: The finishing customer.
    """
    timestamp: int
    line_number: int
    customer: Customer

    def __init__(self, timestamp: int, line_number: int, c: Customer) -> None:
        """Initialize a CheckoutCompleted event.
        """
        # TODO: Implement this method
        super().__init__(timestamp)
        self.line_number = line_number
        self.customer = c

    def do(self, store: GroceryStore) -> list[Event]:
        """
        If a customer finishes checking out, the next customer in the line
        (if there is one) gets a Checkout Started event with the same
        timestamp as the Checkout Completed event.
        """
        # Remove customer from list
        number_in_line = store.remove_front_customer(self.line_number)
        if number_in_line > 0:
            new_checkout = CheckoutStarted(self.timestamp, self.line_number)
            return [new_checkout]
        return None
class CloseLine(Event):
    """A CheckoutLine gets closed.

    Attributes:
    - line_number: The number of the checkout line.
    """
    timestamp: int
    line_number: int

    def __init__(self, timestamp: int, line_number: int) -> None:
        """Initialize a CloseLine event.
        """
        # TODO: Implement this method
        super().__init__(timestamp)
        self.line_number = line_number

    def do(self, store: GroceryStore) -> list[Event]:
        """
        If a line closes, all but the first customer in line needs to go into
        a new line, starting with the customer at the end – essentially they
        re-arrive at the checkout area. So there is one Customer Arrival event
        per customer in the line that is closing (except the first customer).
        The last customer in the line should have a Customer Arrival event
        whose time is the same as the time of the “close line” event, and the
        other Customer Arrival events should follow it in time, spaced 1
        second apart.
        """
        list_cx = store.close_line(self.line_number)
        out_list = []
        incremented_time = self.timestamp
        # If customer exists
        for cx in list_cx[::-1]:
            out_list.append(CustomerArrival(incremented_time, cx))
            incremented_time += 1
        return out_list


EVENT_SAMPLE = StringIO("""121 Arrive William Bananas 7
22 Arrive Trevor Flowers 22 Bread 3 Cheese 3 Cheese 3
41 Close 0""")


def create_event_list(event_file: TextIO) -> list[Event]:
    """Return a list of Event objects to represent the events in <filename>.

    The events in the list must be in the same order as they are in the file.

    Preconditions:
    - <event_file> is open.
    - <event_file> is in the format specified by the assignment handout.

    >>> samp_events = create_event_list(EVENT_SAMPLE)
    >>> len(samp_events) == 3
    True
    >>> isinstance(samp_events[0], CustomerArrival)
    True
    >>> isinstance(samp_events[2], CloseLine)
    True
    """
    # TODO: Implement this function
    result = []
    for line in event_file:
        # Split the line into a list of words
        events = line.strip().split()
        time = int(events[0])
        type_name = events[1]
        if type_name == 'Arrive':
            # Add items to list
            i = 3
            item_list = []
            while i < len(events):
                item_name = events[i]
                item_time = events[i + 1]
                item = Item(item_name, item_time)
                item_list.append(item)
                i += 2
            cx = Customer(events[2], item_list)
            event = CustomerArrival(time, cx)
        else:
            # Close line
            event = CloseLine(time, int(events[2]))
        result.append(event)
    return result


if __name__ == '__main__':
    import doctest

    doctest.testmod()

    check_pyta = True
    if check_pyta:
        import python_ta

        python_ta.check_all(config={
            'allowed-import-modules': ['__future__', 'typing', 'store',
                                       'python_ta', 'doctest', 'io']})
